In [1]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [44]:
train_data = pd.read_csv('/content/drive/MyDrive/KTaivle/3차미니프로젝트/kaggle/train.csv')
test_data = pd.read_csv('/content/drive/MyDrive/KTaivle/3차미니프로젝트/kaggle/test.csv')

In [45]:
train_data.describe()

Unnamed: 0           A_x           A_y           A_z           B_x  \
count  100000.000000  90000.000000  90000.000000  90000.000000  90000.000000   
mean    49999.500000     -0.876639     -0.110566     -0.013331     -0.780543   
std     28867.657797      0.464709      0.348463      0.361989      0.817925   
min         0.000000     -5.132823     -1.949310     -1.284750     -7.483251   
25%     24999.750000     -1.016718     -0.181035     -0.281950     -1.050645   
50%     49999.500000     -0.958268     -0.047425     -0.063756     -0.918144   
75%     74999.250000     -0.764307      0.060235      0.222074     -0.157112   
max     99999.000000      1.849398      2.413866      2.584467      5.372528   

                B_y           B_z          label  
count  90000.000000  90000.000000  100000.000000  
mean       0.116559      0.167377       5.945630  
std        0.593224      0.785482       3.333515  
min       -5.466767     -7.208220       1.000000  
25%       -0.190546     -0.243964       3.000000  
50%        0.023954      0.113276       7.000000  
75%        0.319651      0.525970       9.000000  
max        7.182237      6.766558      11.000000

In [46]:
train_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 9 columns):
 #   Column      Non-Null Count   Dtype  
---  ------      --------------   -----  
 0   Unnamed: 0  100000 non-null  int64  
 1   timestamp   100000 non-null  object 
 2   A_x         90000 non-null   float64
 3   A_y         90000 non-null   float64
 4   A_z         90000 non-null   float64
 5   B_x         90000 non-null   float64
 6   B_y         90000 non-null   float64
 7   B_z         90000 non-null   float64
 8   label       100000 non-null  int64  
dtypes: float64(6), int64(2), object(1)
memory usage: 6.9+ MB


In [47]:
selected_columns = ['label', 'A_x', 'A_y', 'A_z', 'B_x', 'B_y', 'B_z']
selected_data = train_data[selected_columns]

correlation_matrix = selected_data.corr()

label_correlation = correlation_matrix['label']
print("Label과 각 Column들 간의 상관계수:\n", label_correlation)

Label과 각 Column들 간의 상관계수:
 label    1.000000
A_x      0.165722
A_y     -0.275390
A_z      0.315315
B_x      0.207724
B_y      0.065651
B_z      0.223359
Name: label, dtype: float64


In [48]:
train_data.drop(columns = ['Unnamed: 0', 'timestamp'], inplace = True)

In [49]:
train_data = train_data.fillna(train_data.mean())

In [50]:
train_data

A_x       A_y       A_z       B_x       B_y       B_z  label
0     -0.259130 -0.834869 -0.485499  0.196409  0.116559  0.384934      8
1      0.370490  0.175042  0.122625 -0.338242  0.358245  0.126491      2
2     -0.257837 -0.881947 -0.391895  0.196027  0.894537  0.411221      8
3     -0.937753 -0.055961  0.362041 -0.929881  0.087673  0.134609     11
4     -0.988320 -0.190390  0.157909 -0.954669 -0.024810 -0.388420      6
...         ...       ...       ...       ...       ...       ...    ...
99995 -0.499562  0.012127  0.365746 -0.780543 -0.040284 -0.180426     10
99996 -0.929146 -0.110566 -0.362481 -0.951160 -0.047168 -0.344213      3
99997 -0.940124 -0.301950 -0.013331 -0.983245 -0.011691 -0.178657      6
99998 -1.152895 -0.149863 -0.746005 -0.945021 -0.686593  0.317497      5
99999 -0.851409 -0.123314  0.409099 -0.862848 -0.135681 -0.013041     11

[100000 rows x 7 columns]

In [51]:
train_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 7 columns):
 #   Column  Non-Null Count   Dtype  
---  ------  --------------   -----  
 0   A_x     100000 non-null  float64
 1   A_y     100000 non-null  float64
 2   A_z     100000 non-null  float64
 3   B_x     100000 non-null  float64
 4   B_y     100000 non-null  float64
 5   B_z     100000 non-null  float64
 6   label   100000 non-null  int64  
dtypes: float64(6), int64(1)
memory usage: 5.3 MB


In [52]:
def preprocess_with_euclidean_norm(data, AorB):
    x_values = data[AorB + '_x']
    y_values = data[AorB + '_y']
    z_values = data[AorB + '_z']

    euclidean_norm = np.sqrt(x_values**2 + y_values**2 + z_values**2)

    data[AorB + '_euclidean_norm'] = euclidean_norm

    return data

In [53]:
preprocess_with_euclidean_norm(train_data, 'A')
preprocess_with_euclidean_norm(train_data, 'B')

A_x       A_y       A_z       B_x       B_y       B_z  label  \
0     -0.259130 -0.834869 -0.485499  0.196409  0.116559  0.384934      8   
1      0.370490  0.175042  0.122625 -0.338242  0.358245  0.126491      2   
2     -0.257837 -0.881947 -0.391895  0.196027  0.894537  0.411221      8   
3     -0.937753 -0.055961  0.362041 -0.929881  0.087673  0.134609     11   
4     -0.988320 -0.190390  0.157909 -0.954669 -0.024810 -0.388420      6   
...         ...       ...       ...       ...       ...       ...    ...   
99995 -0.499562  0.012127  0.365746 -0.780543 -0.040284 -0.180426     10   
99996 -0.929146 -0.110566 -0.362481 -0.951160 -0.047168 -0.344213      3   
99997 -0.940124 -0.301950 -0.013331 -0.983245 -0.011691 -0.178657      6   
99998 -1.152895 -0.149863 -0.746005 -0.945021 -0.686593  0.317497      5   
99999 -0.851409 -0.123314  0.409099 -0.862848 -0.135681 -0.013041     11   

       A_euclidean_norm  B_euclidean_norm  
0              0.999932          0.447590  
1              0.427714          0.508672  
2              0.998945          1.003856  
3              1.006770          0.943655  
4              1.018803          1.030960  
...                 ...               ...  
99995          0.619257          0.802137  
99996          1.003459          1.012626  
99997          0.987514          0.999412  
99998          1.381358          1.210487  
99999          0.952610          0.873548  

[100000 rows x 9 columns]

In [54]:
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.impute import SimpleImputer
from sklearn.model_selection import train_test_split
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix, classification_report,accuracy_score

X = train_data.drop(columns=['label'])
y = train_data['label']

pipeline = Pipeline([
    ('imputer', SimpleImputer(strategy='mean')),
    ('scaler', StandardScaler()),
    ('classifier', MLPClassifier(hidden_layer_sizes=(100, 50), max_iter=500, random_state=42))
])

X_train, X_val, y_train, y_val = train_test_split(X, y, test_size=0.2, random_state=42)

pipeline.fit(X_train, y_train)

y_pred = pipeline.predict(X_val)

accuracy = accuracy_score(y_val, y_pred)
print("Accuracy:", accuracy)

print(confusion_matrix(y_val, y_pred))
print(classification_report(y_val, y_pred))

Accuracy: 0.84765
[[1748   80   91   53  121   28    2    1    9   35   45]
 [ 175 2079    6    5   45   10    3    1   12  115   20]
 [ 120   16 1219  163  140    4   11    0    4   11    7]
 [  45    0  205 1123   72    1    2    0    3    2   19]
 [ 233   41  166   82  537    1    3    0    3   11    7]
 [  49    4    4    1    1  954    0    0    9   12   49]
 [   2    2    8    0    6    0 2114    0    0    0    2]
 [   5    6    1    1    1    0    0 2238    0    8    4]
 [  42    4    8    1    0    9    2    0 1739   24   26]
 [  61   85    9    6   13   11    0    3   19 1600  141]
 [  23    9    4   17    3   25    2    0   15   81 1602]]
              precision    recall  f1-score   support

           1       0.70      0.79      0.74      2213
           2       0.89      0.84      0.87      2471
           3       0.71      0.72      0.71      1695
           4       0.77      0.76      0.77      1472
           5       0.57      0.50      0.53      1084
           6      

In [55]:
test_data.drop(columns = ['Unnamed: 0', 'timestamp'], inplace = True)

In [58]:
preprocess_with_euclidean_norm(test_data, 'A')
preprocess_with_euclidean_norm(test_data, 'B')

A_x       A_y       A_z       B_x       B_y       B_z  \
0     -1.000957 -0.170691  0.124889 -0.979561  0.003150 -0.264673   
1     -0.874830  0.132696 -0.501727 -1.274911  0.045122  0.121270   
2     -1.219112  0.074678  0.435331 -0.860820  0.222740  0.008689   
3     -0.907752 -0.171816  0.211507 -0.972017  0.337799  1.013534   
4     -1.031261  0.000340 -0.091693 -0.217434 -0.323466  0.931614   
...         ...       ...       ...       ...       ...       ...   
13229 -1.379061  0.070504 -0.528339 -1.154145  0.097546 -0.537505   
13230 -1.039895 -0.122421  0.065954 -1.152930  0.294010  1.080373   
13231 -1.176883 -0.218801 -0.581625 -0.809665  0.126385  0.314077   
13232 -0.912287 -0.148846 -0.141693 -1.382983  0.102818  0.933066   
13233 -1.015306 -0.013448 -0.171994 -0.087205 -0.289400  0.943548   

       A_euclidean_norm  B_euclidean_norm  
0              1.023058          1.014693  
1              1.017185          1.281461  
2              1.296659          0.889213  
3              0.947770          1.444360  
4              1.035330          1.009858  
...                 ...               ...  
13229          1.478487          1.276901  
13230          1.049151          1.607139  
13231          1.330870          0.877597  
13232          0.935147          1.671474  
13233          1.029859          0.990777  

[13234 rows x 8 columns]

In [59]:
test_predictions = pipeline.predict(test_data)

results = pd.DataFrame({'ID': range(len(test_predictions)), 'label': test_predictions})
results.to_csv('sample.csv', index=False)